"""Enumerations for DUAL ENTRY PRECISION V1.4."""
from __future__ import annotations

from enum import Enum


class SymbolStatus(str, Enum):
    IDLE = "IDLE"

    LONG_PULLBACK_ARMED = "LONG_PULLBACK_ARMED"
    SHORT_PULLBACK_ARMED = "SHORT_PULLBACK_ARMED"

    LONG_MOMENTUM_READY = "LONG_MOMENTUM_READY"
    SHORT_MOMENTUM_READY = "SHORT_MOMENTUM_READY"

    ORDER_PENDING = "ORDER_PENDING"

    LONG_OPEN = "LONG_OPEN"
    SHORT_OPEN = "SHORT_OPEN"

    COOLDOWN = "COOLDOWN"
    MODULE_PAUSED = "MODULE_PAUSED"


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class SetupType(str, Enum):
    FAST_PULLBACK = "FAST_PULLBACK"
    MOMENTUM = "MOMENTUM"
    CONFLUENCE = "CONFLUENCE"          # hybrid mode: 3-TF cross trigger


class PullbackType(str, Enum):
    SHALLOW_PULLBACK = "SHALLOW_PULLBACK"
    DEEP_PULLBACK = "DEEP_PULLBACK"
    HTF_ZONE_PULLBACK = "HTF_ZONE_PULLBACK"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"
    LIQUIDITY_SWEEP_PULLBACK = "LIQUIDITY_SWEEP_PULLBACK"


class StructureState(str, Enum):
    STRONG_BULL = "STRONG_BULL"
    BULL = "BULL"
    RANGE = "RANGE"
    TRANSITION = "TRANSITION"
    BEAR = "BEAR"
    STRONG_BEAR = "STRONG_BEAR"


class BiasState(str, Enum):
    STRONG_BULL = "STRONG_BULL"
    BULL = "BULL"
    NEUTRAL = "NEUTRAL"
    BEAR = "BEAR"
    STRONG_BEAR = "STRONG_BEAR"


class RegimeState(str, Enum):
    STRONG_BULL_TREND = "STRONG_BULL_TREND"
    BULL_TREND = "BULL_TREND"
    PULLBACK_TRANSITION_BULL = "PULLBACK_TRANSITION_BULL"
    TRANSITION = "TRANSITION"
    PULLBACK_TRANSITION_BEAR = "PULLBACK_TRANSITION_BEAR"
    BEAR_TREND = "BEAR_TREND"
    STRONG_BEAR_TREND = "STRONG_BEAR_TREND"
    CHOP = "CHOP"


class ZoneType(str, Enum):
    MAJOR_SUPPORT = "MAJOR_SUPPORT"
    MAJOR_RESISTANCE = "MAJOR_RESISTANCE"
    MINOR_SUPPORT = "MINOR_SUPPORT"
    MINOR_RESISTANCE = "MINOR_RESISTANCE"
    DEMAND = "DEMAND"
    SUPPLY = "SUPPLY"
    RANGE_HIGH = "RANGE_HIGH"
    RANGE_LOW = "RANGE_LOW"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"
    FLIPPED_SUPPORT = "FLIPPED_SUPPORT"
    FLIPPED_RESISTANCE = "FLIPPED_RESISTANCE"
    PREVIOUS_DAY_HIGH = "PREVIOUS_DAY_HIGH"
    PREVIOUS_DAY_LOW = "PREVIOUS_DAY_LOW"


class PatternType(str, Enum):
    BREAK_AND_RETEST = "BREAK_AND_RETEST"
    BULL_FLAG = "BULL_FLAG"
    BEAR_FLAG = "BEAR_FLAG"
    COMPRESSION_RANGE = "COMPRESSION_RANGE"
    DOUBLE_BOTTOM = "DOUBLE_BOTTOM"
    DOUBLE_TOP = "DOUBLE_TOP"
    # shadow-mode only (V1.4):
    TRIANGLES = "TRIANGLES"
    HEAD_AND_SHOULDERS = "HEAD_AND_SHOULDERS"
    INVERSE_HEAD_AND_SHOULDERS = "INVERSE_HEAD_AND_SHOULDERS"
    WEDGES = "WEDGES"
    QUASIMODO = "QUASIMODO"


class PatternStatus(str, Enum):
    FORMING = "FORMING"
    VALID = "VALID"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    SHADOW = "SHADOW"


class ConflictLevel(str, Enum):
    NONE = "NONE"
    MILD = "MILD"
    STRONG = "STRONG"


class VolumeMode(str, Enum):
    REAL_VOLUME = "REAL_VOLUME"
    TICK_VOLUME = "TICK_VOLUME"
    PROXY_VOLUME = "PROXY_VOLUME"
    UNAVAILABLE = "UNAVAILABLE"


class ModuleStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REDUCED_RISK = "REDUCED_RISK"
    PAUSED = "PAUSED"
    SHADOW_MODE = "SHADOW_MODE"


class CandleTrigger(str, Enum):
    BULLISH_ENGULFING = "BULLISH_ENGULFING"
    HAMMER = "HAMMER"
    BULLISH_PIN_BAR = "BULLISH_PIN_BAR"
    BULLISH_DISPLACEMENT = "BULLISH_DISPLACEMENT"
    INSIDE_BAR_BREAKOUT = "INSIDE_BAR_BREAKOUT"
    SUPPORT_REJECTION = "SUPPORT_REJECTION"
    BREAKOUT_CLOSE = "BREAKOUT_CLOSE"
    SWEEP_RECLAIM_CANDLE = "SWEEP_RECLAIM_CANDLE"
    BEARISH_ENGULFING = "BEARISH_ENGULFING"
    SHOOTING_STAR = "SHOOTING_STAR"
    BEARISH_PIN_BAR = "BEARISH_PIN_BAR"
    BEARISH_DISPLACEMENT = "BEARISH_DISPLACEMENT"
    RESISTANCE_REJECTION = "RESISTANCE_REJECTION"
    STRONG_CLOSE = "STRONG_CLOSE"
    RECLAIM_CLOSE = "RECLAIM_CLOSE"
    REJECTION_CLOSE = "REJECTION_CLOSE"


class ReasonCode(str, Enum):
    REJECT_DATA_QUALITY = "REJECT_DATA_QUALITY"
    REJECT_STALE_DATA = "REJECT_STALE_DATA"
    REJECT_DUPLICATE_CANDLE = "REJECT_DUPLICATE_CANDLE"
    REJECT_DUPLICATE_SIGNAL = "REJECT_DUPLICATE_SIGNAL"
    REJECT_OPEN_POSITION = "REJECT_OPEN_POSITION"
    REJECT_PENDING_ORDER = "REJECT_PENDING_ORDER"

    REJECT_HTF_BIAS = "REJECT_HTF_BIAS"
    REJECT_4H_STRONG_CONFLICT = "REJECT_4H_STRONG_CONFLICT"
    REJECT_1H_CHOCH = "REJECT_1H_CHOCH"
    REJECT_CHOP = "REJECT_CHOP"

    REJECT_NO_PRIOR_CONTEXT = "REJECT_NO_PRIOR_CONTEXT"
    REJECT_INVALID_LOCATION = "REJECT_INVALID_LOCATION"
    REJECT_WEAK_ZONE = "REJECT_WEAK_ZONE"
    REJECT_STRUCTURE_INVALIDATED = "REJECT_STRUCTURE_INVALIDATED"

    REJECT_BAD_CANDLE = "REJECT_BAD_CANDLE"
    REJECT_NO_TRIGGER = "REJECT_NO_TRIGGER"
    REJECT_NO_BREAKOUT = "REJECT_NO_BREAKOUT"
    REJECT_FALSE_BREAKOUT = "REJECT_FALSE_BREAKOUT"
    REJECT_EXTENSION = "REJECT_EXTENSION"

    REJECT_OPPOSING_ZONE = "REJECT_OPPOSING_ZONE"
    REJECT_LOW_STRUCTURE_ROOM = "REJECT_LOW_STRUCTURE_ROOM"

    REJECT_STOP_TOO_TIGHT = "REJECT_STOP_TOO_TIGHT"
    REJECT_STOP_TOO_WIDE = "REJECT_STOP_TOO_WIDE"
    REJECT_LOW_RR = "REJECT_LOW_RR"

    REJECT_CORRELATION = "REJECT_CORRELATION"
    REJECT_TOTAL_RISK = "REJECT_TOTAL_RISK"

    REJECT_MODULE_PAUSED = "REJECT_MODULE_PAUSED"
    REJECT_VOLATILITY_SHOCK = "REJECT_VOLATILITY_SHOCK"

    REJECT_EXECUTION_QUALITY = "REJECT_EXECUTION_QUALITY"
    REJECT_SIGNAL_EXPIRED = "REJECT_SIGNAL_EXPIRED"
    REJECT_SLIPPAGE = "REJECT_SLIPPAGE"
    REJECT_SPREAD = "REJECT_SPREAD"
    REJECT_MARKET_CLOSED = "REJECT_MARKET_CLOSED"

    REJECT_THRESHOLD = "REJECT_THRESHOLD"
    REJECT_DIRECTIONAL_AMBIGUITY = "REJECT_DIRECTIONAL_AMBIGUITY"
    REJECT_COOLDOWN = "REJECT_COOLDOWN"
    REJECT_MAX_POSITIONS = "REJECT_MAX_POSITIONS"
    REJECT_LOW_VOLUME = "REJECT_LOW_VOLUME"
    VOLATILITY_SHOCK = "VOLATILITY_SHOCK"


class ExitReason(str, Enum):
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    BREAKEVEN_STOP = "BREAKEVEN_STOP"
    HARD_STRUCTURE_INVALIDATION = "HARD_STRUCTURE_INVALIDATION"
    HARD_FLIP = "HARD_FLIP"
    EARLY_EXIT = "EARLY_EXIT"
    FALSE_BREAKOUT = "FALSE_BREAKOUT"
    MANUAL = "MANUAL"
    EMERGENCY_PROTECTION = "EMERGENCY_PROTECTION"
    EXTERNAL = "EXTERNAL"
